# Generated by Django 6.1 on 2026-08-28 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arbitres', '0001_initial'),
        ('boxeurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('edition', models.CharField(default='Edition 2026', max_length=100)),
                ('date_evenement', models.DateTimeField()),
                ('lieu', models.CharField(default='Dome Arena', max_length=200)),
                ('duree_round_secondes', models.PositiveIntegerField(default=180)),
                ('nombre_rounds', models.PositiveIntegerField(default=3)),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_rouge', models.PositiveIntegerField()),
                ('points_bleu', models.PositiveIntegerField()),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Combat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_match', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('A_VENIJ', 'A venir'), ('EN_COURS', 'En cours'), ('TERMINE', 'Termine'), ('EN_PAUSE', 'En pause')], default='A_VENIR', max_length=20)),
                ('coin_vainqueur', models.CharField(blank=True, choices=[('ROUGE', 'Coin Rouge'), ('BLEU', 'Coin Bleu'), ('EGALITE', 'Egalite')], max_length=10, null=True)),
                ('type_decision', models.CharField(blank=True, max_length=100, null=True)),
                ('arbitre_central', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arbitres.arbitrecentral')),
                ('boxeur_bleu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combats_bleu', to='boxeurs.boxeur')),
                ('boxeur_rouge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combats_rouge', to='boxeurs.boxeur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxeurs.categorie')),
                ('vainqueur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_gagnes', to='boxeurs.boxeur')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combats', to='combats.evenement')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_round', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Termine')], default='EN_ATTENTE', max_length=20)),
                ('total_score_rouge', models.PositiveIntegerField(default=0)),
                ('total_score_bleu', models.PositiveIntegerField(default=0)),
                ('coin_gagnant_round', models.CharField(blank=True, choices=[('ROUGE', 'Coin Rouge'), ('BLEU', 'Coin Bleu'), ('EGALITE', 'Egalite')], max_length=10, null=True)),
                ('combat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='combats.combat')),
            ],
        ),
    ]
