# Generated by Django 6.1 on 2026-08-28 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scorejury',
            name='juge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_attribues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scorejury',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_jury', to='combats.round'),
        ),
        migrations.AlterUniqueTogether(
            name='scorejury',
            unique_together={('round', 'juge')},
        ),
    ]
