# Generated by Django 6.1 on 2026-08-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='combat',
            name='statut',
            field=models.CharField(choices=[('A_VENIR', 'A venir'), ('EN_COURS', 'En cours'), ('TERMINE', 'Termine'), ('EN_PAUSE', 'En pause')], default='A_VENIR', max_length=20),
        ),
    ]
