# Generated by Django 6.1 on 2026-08-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combats', '0003_round_valide_alter_combat_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combat',
            name='type_decision',
            field=models.CharField(blank=True, choices=[('POINTS', 'Décision aux Points (10-Point Must)'), ('KO', 'K.O. (Knockout)'), ('TKO', 'T.K.O. (Technique K.O. / Arrêt Arbitre)'), ('SOUMISSION', 'Soumission (Clef / Étranglement)'), ('ABANDON', 'Abandon'), ('ARRET_MEDICAL', 'Arrêt Médical'), ('DISQUALIFICATION', 'Disqualification')], default='POINTS', max_length=100, null=True),
        ),
    ]
