# Generated by Django 6.1 on 2026-08-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combats', '0004_alter_combat_type_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='federation',
            field=models.CharField(default='COMITÉ NATIONAL PROVISOIRE DE MMA ET DISCIPLINES ASSOCIÉES (CNP-MMA/DA)', max_length=250),
        ),
        migrations.AddField(
            model_name='evenement',
            name='logo_aes',
            field=models.ImageField(blank=True, help_text='Logo Confédération AES', null=True, upload_to='logos_evenements/'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='logo_discipline',
            field=models.ImageField(blank=True, help_text='Logo Sports de Combat / MMA', null=True, upload_to='logos_evenements/'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='logo_evenement',
            field=models.ImageField(blank=True, help_text='Logo officiel des JAES 2026', null=True, upload_to='logos_evenements/'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='logo_ministere',
            field=models.ImageField(blank=True, help_text='Logo du Ministère MSJE Burkina Faso', null=True, upload_to='logos_evenements/'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='nom_discipline',
            field=models.CharField(default='MIXED MARTIAL ARTS (MMA)', max_length=150),
        ),
        migrations.AddField(
            model_name='evenement',
            name='organisateur',
            field=models.CharField(default="Ministère des Sports, de la Jeunesse et de l'Emploi MSJE / BURKINA FASO", max_length=250),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_evenement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='edition',
            field=models.CharField(default='Ouagadougou 2026', max_length=100),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='lieu',
            field=models.CharField(default='Palais des Sports de Ouagadougou (Burkina Faso)', max_length=200),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(default="2ème édition des Jeux de l'Alliance des États du Sahel (JAES) 2026", max_length=200),
        ),
    ]
