# Generated by Django 6.1 on 2026-08-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combats', '0005_evenement_federation_evenement_logo_aes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='couleur_fond_header',
            field=models.CharField(default='#B91C1C', help_text="Couleur Hex/CSS de fond de l'en-tête (ex: #B91C1C pour Rouge Fédéral)", max_length=50),
        ),
        migrations.AddField(
            model_name='evenement',
            name='couleur_texte_header',
            field=models.CharField(default='#FFFFFF', help_text="Couleur Hex/CSS du texte de l'en-tête", max_length=50),
        ),
        migrations.AddField(
            model_name='evenement',
            name='image_banniere_header',
            field=models.ImageField(blank=True, help_text="Image de bannière officielle pour l'en-tête (optionnelle)", null=True, upload_to='bannieres_evenements/'),
        ),
    ]
