# Generated by Django 6.1 on 2026-08-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combats', '0006_evenement_couleur_fond_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='drapeau_arriere_plan',
            field=models.ImageField(blank=True, help_text="Image du drapeau national/fédéral flottant pour l'arrière-plan de la page de connexion", null=True, upload_to='drapeaux_evenements/'),
        ),
    ]
