# Generated by Django 6.1 on 2026-08-29 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitres', '0002_arbitrecentral_pays_alter_arbitrecentral_photo'),
        ('combats', '0007_evenement_drapeau_arriere_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='date_combat',
            field=models.DateField(blank=True, help_text='Date programmée pour ce combat', null=True, verbose_name='Date du combat'),
        ),
        migrations.AddField(
            model_name='combat',
            name='heure_combat',
            field=models.TimeField(blank=True, help_text='Heure prévue pour ce combat (ex: 16:30)', null=True, verbose_name='Heure du combat'),
        ),
        migrations.AddField(
            model_name='combat',
            name='juges',
            field=models.ManyToManyField(blank=True, help_text='Juges de table affectés à ce combat', related_name='combats_juges', to=settings.AUTH_USER_MODEL, verbose_name='Juges affectés (Jury)'),
        ),
        migrations.AlterField(
            model_name='combat',
            name='arbitre_central',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arbitres.arbitrecentral', verbose_name='Arbitre Central Ring'),
        ),
    ]
