# Generated by Django 6.1 on 2026-08-29 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combats', '0008_combat_date_combat_combat_heure_combat_combat_juges_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='juge_principal',
            field=models.ForeignKey(blank=True, help_text='Juge Principal responsable de la supervision de ce combat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_juge_principal', to=settings.AUTH_USER_MODEL, verbose_name='Juge Principal (Chef Table)'),
        ),
        migrations.AlterField(
            model_name='combat',
            name='juges',
            field=models.ManyToManyField(blank=True, help_text='Juges de table affectés à ce combat', related_name='combats_juges', to=settings.AUTH_USER_MODEL, verbose_name='Juges de Table (Jury)'),
        ),
    ]
