# Generated by Django 6.1 on 2026-08-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combats', '0009_combat_juge_principal_alter_combat_juges'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='media_regie_image',
            field=models.ImageField(blank=True, null=True, upload_to='medias_regie/', verbose_name='Photo / Replay Coup Marquant Régie'),
        ),
        migrations.AddField(
            model_name='combat',
            name='media_regie_titre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre / Légende du Média Régie'),
        ),
        migrations.AddField(
            model_name='combat',
            name='mode_tv',
            field=models.CharField(choices=[('ATTENTE_PUB', 'Écran Attente & Sponsors / Pubs'), ('CARTE_PROGRAMME', 'Programme des 5 prochains combats'), ('PRESENTATION_COMBATTANTS', 'Présentation Tale of the Tape Combattants'), ('PRESENTATION_OFFICIELS', 'Présentation Arbitre & Jury'), ('LANCEMENT_ROUND', 'Annonce Départ de Round (Grand Format)'), ('COMBAT_EN_COURS', 'Scoring & Chrono Combat en Direct'), ('MEDIA_HIGHLIGHT', 'Replay / Photo Coup Marquant en Direct'), ('PROCLAMATION_VAINQUEUR', 'Célébration & Décision Officielle')], default='ATTENTE_PUB', max_length=30, verbose_name="Mode d'affichage Régie TV Broadcast"),
        ),
    ]
