# Generated by Django 6.1 on 2026-08-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combats', '0010_combat_media_regie_image_combat_media_regie_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='image_ring_bg',
            field=models.ImageField(blank=True, help_text="Image HD personnalisée de l'arrière-plan du Ring pour ce match", null=True, upload_to='rings_backgrounds/', verbose_name='Image de Fond du Ring / Octogone pour ce Combat'),
        ),
        migrations.AlterField(
            model_name='combat',
            name='mode_tv',
            field=models.CharField(choices=[('ATTENTE_PUB', 'Écran Attente & Sponsors / Pubs'), ('CARTE_PROGRAMME', 'Programme des 5 prochains combats'), ('PRESENTATION_ROUGE_SOLO', 'Présentation Solo Coin Rouge (Plein Écran)'), ('PRESENTATION_BLEU_SOLO', 'Présentation Solo Coin Bleu (Plein Écran)'), ('PRESENTATION_FACE_A_FACE', 'Confrontation Face-à-Face dans le Ring'), ('PRESENTATION_COMBATTANTS', 'Présentation Tale of the Tape Combattants'), ('PRESENTATION_OFFICIELS', 'Présentation Arbitre & Jury'), ('LANCEMENT_ROUND', 'Annonce Départ de Round (Grand Format)'), ('COMBAT_EN_COURS', 'Scoring & Chrono Combat en Direct'), ('MEDIA_HIGHLIGHT', 'Replay / Photo Coup Marquant en Direct'), ('PROCLAMATION_VAINQUEUR', 'Célébration & Décision Officielle')], default='ATTENTE_PUB', max_length=35, verbose_name="Mode d'affichage Régie TV Broadcast"),
        ),
    ]
