# Generated by Django 6.1 on 2026-08-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combats', '0011_combat_image_ring_bg_alter_combat_mode_tv'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='audio_victoire',
            field=models.FileField(blank=True, help_text='Fichier audio (MP3/WAV) joué lors de la proclamation du vainqueur', null=True, upload_to='audios_victoire/', verbose_name='Musique / Hymne de Victoire Audio'),
        ),
        migrations.AlterField(
            model_name='combat',
            name='mode_tv',
            field=models.CharField(choices=[('ATTENTE_PUB', 'Écran Attente & Sponsors / Pubs'), ('CARTE_PROGRAMME', 'Programme des 5 prochains combats'), ('PRESENTATION_ROUGE_SOLO', 'Présentation Solo Coin Rouge (Plein Écran)'), ('PRESENTATION_BLEU_SOLO', 'Présentation Solo Coin Bleu (Plein Écran)'), ('PRESENTATION_FACE_A_FACE', 'Confrontation Face-à-Face dans le Ring'), ('PRESENTATION_COMBATTANTS', 'Présentation Tale of the Tape Combattants'), ('PRESENTATION_OFFICIELS', 'Présentation Arbitre & Jury'), ('LANCEMENT_ROUND', 'Annonce Départ de Round (Grand Format)'), ('COMBAT_EN_COURS', 'Scoring & Chrono Combat en Direct'), ('MEDIA_HIGHLIGHT', 'Replay / Photo Coup Marquant en Direct'), ('DECISION_RECAP', 'Tableau Récapitulatif des Scores (Round par Round)'), ('PROCLAMATION_VAINQUEUR', 'Célébration & Décision Officielle')], default='ATTENTE_PUB', max_length=35, verbose_name="Mode d'affichage Régie TV Broadcast"),
        ),
    ]
