# Generated by Django 6.1 on 2026-08-31 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combats', '0012_combat_audio_victoire_alter_combat_mode_tv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoreJury',
        ),
    ]
