# Generated by Django 6.1 on 2026-08-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combats', '0013_delete_scorejury'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='decision_qualification',
            field=models.CharField(blank=True, help_text='Décision Unanime, Décision Partagée, Décision Majoritaire, KO, TKO, Soumission, etc.', max_length=50, null=True, verbose_name='Qualification officielle'),
        ),
        migrations.AddField(
            model_name='combat',
            name='details_decision',
            field=models.CharField(blank=True, help_text='Technique ou récapitulatif des cartes (ex: 30-27, 29-28, 30-27)', max_length=250, null=True, verbose_name='Détails de la décision'),
        ),
        migrations.AddField(
            model_name='combat',
            name='round_fin',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Round d'arrêt du combat"),
        ),
        migrations.AddField(
            model_name='combat',
            name='temps_fin_round',
            field=models.CharField(blank=True, help_text="Temps exact du chrono au moment de l'arrêt (ex: 01:42)", max_length=20, null=True, verbose_name="Temps / Minute de l'arrêt"),
        ),
    ]
