# Generated by Django 6.1 on 2026-08-28 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combats', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreJuge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pts_rouge', models.IntegerField(default=10, verbose_name='Points Boxeur Rouge')),
                ('pts_bleu', models.IntegerField(default=9, verbose_name='Points Boxeur Bleu')),
                ('date_saisie', models.DateTimeField(auto_now=True)),
                ('juge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_attribues_scoring', to=settings.AUTH_USER_MODEL, verbose_name='Juge')),
                ('round_combat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_juges', to='combats.round', verbose_name='Round')),
            ],
            options={
                'verbose_name': 'Score Juge',
                'verbose_name_plural': 'Scores Juges',
                'unique_together': {('round_combat', 'juge')},
            },
        ),
    ]
