# Generated by Django 6.1 on 2026-08-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrecentral',
            name='pays',
            field=models.CharField(default='Burkina Faso', max_length=100),
        ),
        migrations.AlterField(
            model_name='arbitrecentral',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='arbitres/'),
        ),
    ]
