# Generated by Django 6.1 on 2026-08-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitres', '0002_arbitrecentral_pays_alter_arbitrecentral_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arbitrecentral',
            options={'verbose_name': 'Arbitre Central', 'verbose_name_plural': 'Arbitres Centraux'},
        ),
        migrations.AddField(
            model_name='arbitrecentral',
            name='sexe',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], default='Masculin', max_length=20, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='arbitrecentral',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='arbitrecentral',
            name='pays',
            field=models.CharField(default='Burkina Faso', max_length=100, verbose_name='Pays / Nationalité'),
        ),
        migrations.AlterField(
            model_name='arbitrecentral',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='arbitres/', verbose_name='Photo officielle'),
        ),
        migrations.AlterField(
            model_name='arbitrecentral',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
    ]
