# Generated by Django 6.1 on 2026-08-31 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitres', '0003_alter_arbitrecentral_options_arbitrecentral_sexe_and_more'),
        ('boxeurs', '0003_boxeur_date_naissance_alter_boxeur_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrecentral',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge'),
        ),
        migrations.AddField(
            model_name='arbitrecentral',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Naissance'),
        ),
        migrations.AddField(
            model_name='arbitrecentral',
            name='pays_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitres', to='boxeurs.pays', verbose_name='Pays Officiel'),
        ),
    ]
