# Generated by Django 6.1 on 2026-08-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='fonction',
            field=models.CharField(blank=True, help_text='Ex: Président de séance, Médecin officiel, Chronométreur, etc.', max_length=100, null=True, verbose_name='Fonction / Titre'),
        ),
    ]
