# Generated by Django 6.1 on 2026-08-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_utilisateur_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, help_text="Photo d'identité / portrait officiel du juge", null=True, upload_to='juges_photos/', verbose_name='Photo Officielle'),
        ),
    ]
