# Generated by Django 6.1 on 2026-08-28 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=20)),
                ('poids_minimum', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('poids_maximum', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Boxeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('surnom', models.CharField(blank=True, max_length=100, null=True)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], default='Masculin', max_length=20)),
                ('pays', models.CharField(default='Burkina Faso', max_length=100)),
                ('club', models.CharField(max_length=150)),
                ('logo_club', models.ImageField(blank=True, null=True, upload_to='logos_clubs/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='boxeurs/')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('taille_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('poids_pesee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxeurs.categorie')),
            ],
        ),
    ]
