# Generated by Django 6.1 on 2026-08-31 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxeurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du Pays')),
                ('code_iso', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code ISO (ex: BF)')),
                ('drapeau', models.ImageField(blank=True, null=True, upload_to='drapeaux_pays/', verbose_name='Image du Drapeau HD')),
                ('drapeau_emoji', models.CharField(blank=True, default='🏳️', max_length=10, verbose_name='Emoji Drapeau')),
                ('est_membre_aes', models.BooleanField(default=False, verbose_name="Membre de l'AES")),
            ],
            options={
                'verbose_name': 'Pays / Nation',
                'verbose_name_plural': 'Pays / Nations',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='boxeur',
            name='pays_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxeurs', to='boxeurs.pays', verbose_name='Pays Officiel'),
        ),
    ]
