# Generated by Django 6.1 on 2026-08-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxeurs', '0002_pays_boxeur_pays_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxeur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Naissance'),
        ),
        migrations.AlterField(
            model_name='boxeur',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge (calculé)'),
        ),
    ]
