# Generated by Django 6.1 on 2026-09-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxeurs', '0003_boxeur_date_naissance_alter_boxeur_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['genre', 'poids_maximum'], 'verbose_name': 'Catégorie de Poids', 'verbose_name_plural': 'Catégories de Poids'},
        ),
        migrations.AlterField(
            model_name='boxeur',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge'),
        ),
        migrations.AlterField(
            model_name='boxeur',
            name='club',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Club / Équipe'),
        ),
    ]
