# Generated by Django 6.1 on 2026-09-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxeurs', '0004_alter_categorie_options_alter_boxeur_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxeur',
            name='musique_victoire',
            field=models.FileField(blank=True, help_text='Fichier audio (MP3/WAV) propre à ce combattant', null=True, upload_to='musiques_boxeurs/', verbose_name='Musique / Hymne de Victoire Personnalisé'),
        ),
    ]
